#!/usr/bin/env bash
#
# claude-charter UserPromptSubmit hook — skill router
#
# Claude Code invokes this script on every user prompt submission. The
# script reads the prompt from stdin JSON, classifies the task type by
# keyword matching, and injects a skill-use instruction into the prompt
# context via `hookSpecificOutput.additionalContext`.
#
# Rationale: Phase B Run 1 (2026-04-15, charter v0.1.1, multi-mind real
# codebase) demonstrated that description-based skill triggering is
# unreliable on real projects — the agent may read the skill
# descriptions, recognize their existence, and still bypass them because
# the task prompt doesn't precisely match the listed triggers. This hook
# closes the gap by pattern-matching the prompt and explicitly
# instructing the model to invoke the relevant skill.
#
# The hook is ADDITIVE, never blocking. If no pattern matches, stdout
# is empty and Claude Code proceeds normally. False negatives degrade
# silently to the pre-hook behavior; false positives instruct the model
# to invoke a skill that may not apply, which costs one extra tool call
# but does not break anything.

set -u

# Require jq for safe JSON I/O. If missing, exit cleanly.
if ! command -v jq >/dev/null 2>&1; then
    exit 0
fi

INPUT=$(cat 2>/dev/null || echo "{}")
PROMPT=$(printf '%s' "$INPUT" | jq -r '.prompt // ""' 2>/dev/null || echo "")

if [ -z "$PROMPT" ]; then
    exit 0
fi

# Lowercase for case-insensitive substring matching.
PROMPT_LC=$(printf '%s' "$PROMPT" | tr '[:upper:]' '[:lower:]')

match_any() {
    local needle
    for needle in "$@"; do
        if printf '%s' "$PROMPT_LC" | grep -q -F -- "$needle"; then
            return 0
        fi
    done
    return 1
}

SKILLS=()

# context-gathering — task touches code the agent hasn't read this session
if match_any \
    "fix" "bug" "broken" "error" "crash" "fails" "doesn't work" "regression" \
    "add " "adding" "implement" "create" "build" "feature" "extend" \
    "refactor" "rewrite" "cleanup" "modernize" "migrate" \
    "modify" "change" "update " "edit " \
    "explain" "how does" "walk me through" "trace" \
    "ekle" "eklen" "düzelt" "yap" "değiştir" "refaktör" \
    "anlat" "hata" "bozuk" "çalışmıyor" "düzeltme" ; then
    SKILLS+=("context-gathering")
fi

# quality — task will produce a commit or change behavior
if match_any \
    "fix" "add " "adding" "implement" "make it work" "make tests pass" \
    "resolve" "refactor" "change" "modify" "update " "rewrite" \
    "get rid of" "remove " "delete " \
    "ekle" "düzelt" "yap" "değiştir" "refaktör" "çöz" "kaldır" "sil" ; then
    SKILLS+=("quality")
fi

# git-ops — explicit git / PR / branch work
if match_any \
    "commit" "branch" "push" " pr " "pull request" "merge" "rebase" \
    "stage " "git " "tag" "release" \
    "commit et" "branch aç" "merge et" "pr aç" "push et" ; then
    SKILLS+=("git-ops")
fi

# security-review — auth, secrets, input parsing, queries, boundaries
if match_any \
    "auth" "login" "password" "token" "secret" "api key" "credential" \
    "session" "sql" "injection" "xss" "upload" "eval" "exec" \
    "deserialize" "cors" "csrf" "permission" " role " "access control" \
    "şifre" "parola" "jeton" "yetki" "giriş" "oturum" "güvenlik" ; then
    SKILLS+=("security-review")
fi

if [ ${#SKILLS[@]} -eq 0 ]; then
    exit 0
fi

DEDUPED=$(printf '%s\n' "${SKILLS[@]}" | sort -u)

MSG="[charter prompt-router]"$'\n'"This task matches the triggers for the following charter skill(s). You MUST invoke each via the Skill tool BEFORE your first Read/Write/Edit/Grep/Glob/Bash tool call on the task:"$'\n'
while IFS= read -r skill; do
    MSG+="  - ${skill}"$'\n'
done <<< "$DEDUPED"
MSG+=$'\n'"This instruction is generated by scripts/prompt-router.sh based on keyword matching against the user prompt. If a match is a false positive, invoke the skill anyway (a cheap read) and continue — do not litigate the routing. If a skill you believe applies is missing from the list, invoke it anyway. Skill invocation is cheap; bypassing a procedure is expensive."

jq -cn --arg ctx "$MSG" \
    '{hookSpecificOutput: {hookEventName: "UserPromptSubmit", additionalContext: $ctx}}'

exit 0
